# Config file for devicehub-client

# Copy this file to the root folder of the project.
# Each root property is a config environment (ex. 'development').
# 'default' is a base config environment for the rest ones.

# When building with gulp, pass-in an environment variable
# to select which environment config you want to use.
# The env. variable must be called `DH_ENV`. Ex. `export DH_ENV=development`.
# If no variable is set, by default it is used `development`.

# In the following case 'development' env adds 'url' setting and
# overrides 'debug' setting from the default one.

default:
  CONSTANTS:
    appName: DeviceHub
    html5mode: false  # If true, uncomment the line in the header in index.html
    siteLogo: common/assets/devicehub-logo.svg
    eReuseLogo: common/assets/ereuse-logo.svg
    defaultLabelLogo: common/assets/devicehub-logo-label.png
    loginBackgroundImage: common/assets/login-background.jpg
    headers:
      Content-Type: application/json
      Accept: application/json
    debug: false
    currency: €
    workbenchPollingDelay: 2650
    workbench: localhost
    androidWorkbench: 192.168.12.1
development:
  CONSTANTS:
    url: http://localhost:5000
    debug: true
tutorial:
    CONSTANTS:
      appName: Devicehub Beta
      blockchain: '127.0.0.1'
      html5mode: true
      url: https://localhost:5000
      inventories: true
